services:
    siwapp_invoice.form.type.invoice:
        class: Siwapp\InvoiceBundle\Form\InvoiceType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
    siwapp_invoice.listener.item_listener:
        class: Siwapp\InvoiceBundle\EventListener\ItemListener
        tags:
            - { name: doctrine.event_listener, event: onFlush }