<?php

namespace Siwapp\CategoryBundle\Repository;

use Knp\Component\Pager\PaginatorInterface;
use Siwapp\InvoiceBundle\Entity\Invoice;
use Siwapp\CategoryBundle\Entity\Category;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function createCategoryQueryBuilder()
    {
        return $this->createQueryBuilder('category')
            ->orderBy('category.categoryName', 'ASC');
    }

    public function validateStock(string $category): array
    {
        return $this->getEntityManager()
        ->createQueryBuilder()
        ->select('c')
        ->from(Category::class, 'c')
        ->where('c.categoryName = :category')
        ->setParameter('category', $category)
        ->getQuery()
        ->getResult();
    }
    
    public function findLikeReference(string $term): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from(Category::class, 'c')
            ->where('c.categoryName LIKE :term')
            ->setParameter('term', '%'. $term .'%')
            ->getQuery()
            ->getResult();
    }

    public function paginatedSearch(array $params, $limit = 50, $page = 1)
    {
        if (!$this->paginator) {
            throw new \RuntimeException('You have to set a paginator first using setPaginator() method');
        }

        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from(Category::class, 'c');
        foreach ($params as $field => $value) {
            if ($value === null) {
                continue;
            }
            if ($field == 'terms') {
                $terms = $qb->expr()->literal("%$value%");
                $qb->andWhere($qb->expr()->orX(
                    $qb->expr()->like('c.categoryName', $terms),
                    $qb->expr()->like('c.description', $terms)
                ));
            }
        }

        return $this->paginator->paginate($qb->getQuery(), $page, $limit);
    }

    /**
     * There is no easy way to inject things into repositories yet.
     */
    public function setPaginator(PaginatorInterface $paginator)
    {
        $this->paginator = $paginator;
    }
}
