services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.siwapp_core:
        class: Siwapp\CoreBundle\Extension\SiwappCoreTwigExtension
        arguments: ['%kernel.bundles%']
        tags:
            - { name: twig.extension }
    siwapp_core.html_page_merger:
        class: Siwapp\CoreBundle\HtmlPageMerger

    siwapp_core.form.type.item:
        class: Siwapp\CoreBundle\Form\ItemType
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: form.type }
