<?php

namespace Siwapp\EstimateBundle\Repository;

use Siwapp\CoreBundle\Entity\Series;
use Siwapp\CoreBundle\Repository\AbstractInvoiceRepository;
use Siwapp\EstimateBundle\Entity\Estimate;
use Siwapp\CustomerBundle\Entity\Customer;

/**
 * EstimateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstimateRepository extends AbstractInvoiceRepository
{
}
