<?php

namespace Siwapp\OrderBundle\Repository;

use Siwapp\CoreBundle\Entity\Series;
use Siwapp\CoreBundle\Repository\AbstractInvoiceRepository;
use Siwapp\OrderBundle\Entity\Order;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends AbstractInvoiceRepository
{
}
