services:
    siwapp_user.locale_listener:
        class: Siwapp\UserBundle\EventListener\LocaleListener
        arguments: ['%kernel.default_locale%']
        tags:
            - { name: kernel.event_subscriber }
    siwapp_user.user_locale_listener:
        class: Siwapp\UserBundle\EventListener\UserLocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    siwapp_user.fos_user_events_listener:
        class: Siwapp\UserBundle\EventListener\FosUserEventsListener
        tags:
            - { name: kernel.event_subscriber }
    siwapp_user.form.profile:
        class: Siwapp\UserBundle\Form\ProfileFormType
        tags:
            - { name: form.type, alias: siwapp_user_user_profile }
    siwapp_user.mailer.siwapp:
        class: Siwapp\UserBundle\Mailer\SiwappUserMailer
        arguments: ['@mailer', '@router', '@templating', {
            confirmation.template: '%fos_user.registration.confirmation.template%',
            resetting.template: '%fos_user.resetting.email.template%',
            from_email: {
                confirmation: '%fos_user.registration.confirmation.from_email%',
                resetting: '%fos_user.resetting.email.from_email%',
            }},
            '@doctrine.orm.entity_manager']
